- name: Añadir repositorio Jenkins
     shell: wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -
     become: yes

   - name: Añadimos repositorio al sistema
     shell: sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
     become: yes

   - name: actualizando apt package cache
     become: yes
     action: apt update_cache=yes

   - name: Instalando Jenkins
     apt:
        name: jenkins
        state: present
        install_recommends: yes
     become: true
